# Generated by Django 5.2.3 on 2025-06-20 22:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CrossConnect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Descriptive name of the cross-connect (e.g., 'Fibre ODF - Rack 1')", max_length=200)),
                ('source', models.CharField(help_text='Source port/device', max_length=100)),
                ('destination', models.CharField(help_text='Destination port/device', max_length=100)),
                ('connection_type', models.CharField(help_text="Type of connection (e.g., '10 GbE', 'Fibre Channel')", max_length=50)),
                ('status', models.CharField(default='Active', help_text="Status of the connection (e.g., 'Active', 'Inactive')", max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PDUFeed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Name of the PDU feed (e.g., 'PDU Feed 1 (Active)')", max_length=100, unique=True)),
                ('status', models.CharField(default='Online', help_text="Current status (e.g., 'Online', 'Standby', 'Offline')", max_length=50)),
                ('capacity_kw', models.DecimalField(blank=True, decimal_places=2, help_text='Capacity of the PDU feed in kW', max_digits=5, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Unique name for the rack (e.g., 'Comm Rack', 'Servers Rack')", max_length=100, unique=True)),
                ('location', models.CharField(blank=True, help_text='Physical location within the data center', max_length=200, null=True)),
                ('total_units', models.IntegerField(default=42, help_text='Total rack units (U) available in this rack')),
                ('max_power_capacity_kw', models.DecimalField(decimal_places=2, default=4.0, help_text='Maximum power capacity (kW) of the rack', max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='SensorData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor_type', models.CharField(choices=[('Power Draw', 'Power Draw (kW)'), ('Inlet Temp', 'Inlet Temperature (°C)'), ('Humidity', 'Humidity (% RH)'), ('CPU Load', 'CPU Load (%)'), ('Disk I/O', 'Disk I/O (%)'), ('Network Traffic', 'Network Traffic (%)'), ('Airflow Pressure', 'Airflow Pressure (Pa)'), ('DC Output Voltage', 'DC Output Voltage (V)'), ('Rectifier Temp', 'Rectifier Temperature (°C)')], max_length=50)),
                ('value', models.DecimalField(decimal_places=2, max_digits=8)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('rack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.rack')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
